PART:=1

.PHONY: oscillator poisson rnumber rwalk diffusion gases

oscillator:
	python oscillator.py --part=$(PART)

poisson:
	python poisson.py --part=$(PART)

rnumbers:
	python rnumbers.py --part=$(PART)

rwalk:
	python rwalk.py --part=$(PART)

diffusion:
	python diffusion.py --part=$(PART)

gases:
	python gases.py --part=$(PART)

